---
# roles/jupyterhub/tasks/main.yml
# 
# deploys and launches jupyterhub

- name: establish jupyterhub directory
  file:
    path: "{{ jh_root_dir }}"
    state: directory
    mode: 0755

- name: copy jupyterhub service directory from templates
  template: 
    src: "{{ item }}" 
    dest: "{{ jh_root_dir }}/{{ item | basename | regex_replace('\\.j2','') }}"
  with_fileglob:
    - templates/*.j2

- name: ensure db and data volumes exists
  docker_volume:
    name: "{{ item }}"
    driver: local
    state: present
  with_items:
    - "{{ DB_VOLUME_HOST }}"
    - "{{ DATA_VOLUME_HOST }}"

- name: ensure hub network exists
  docker_network:
    name: "{{ DOCKER_NETWORK_NAME }}"
    driver: bridge

# Pull all valid single user images.
- name: pull singleuser images
  docker_image:
    name: "{{ item }}"
    state: present
  with_items: "{{ jh_singleuser_images }}"

#- name: add nginx virtual host configuration
#  template:
#    src: templates/nginx_virtual_host.conf.j2
#    dest: "{{ proxy_dir }}/vhost.d/{{ jh_domain }}"

# name: add jupyterhub configuration
# template:
#   src: templates/app.ini.j2
#   dest: "{{ jh_root_dir }}/data/jupyterhub/conf/app.ini"

- name: Include SSL Plays
  include: ssl.yml
  tags:
    - ssl

- name: start jupyterhub
  docker_service:
    project_src: "{{ jh_root_dir }}"
    state: present
    build: yes
    restarted: yes
