---
# roles/jupyterhub/tasks/main.yml
# 
# deploys and launches jupyterhub

- name: establish jupyterhub directory
  file:
    path: "{{ jh_root_dir }}"
    state: directory
    mode: 0755

- name: copy jupyterhub service directory from templates
  template: 
    src: "{{ item }}" 
    dest: "{{ jh_root_dir }}/{{ item | basename | regex_replace('\\.j2','') }}"
  with_fileglob:
    - templates/*.j2
  tags:
    - hub_config

- name: ensure db and data volumes exists
  docker_volume:
    name: "{{ item }}"
    driver: local
    state: present
  with_items:
    - "{{ jh_db_volume_host }}"
    - "{{ jh_data_volume_host }}"

- name: ensure hub network exists
  docker_network:
    name: "{{ jh_docker_network }}"
    driver: bridge

- name: pull singleuser images
  docker_image:
    name: "{{ item }}"
    state: present
  with_items: "{{ jh_singleuser_images }}"

- name: Include SSL Plays
  include: ssl.yml
  tags:
    - ssl

- name: start jupyterhub
  docker_service:
    project_src: "{{ jh_root_dir }}"
    state: present
    build: yes
    restarted: yes
  tags:
    - hub_config
