# vi: ft=Dockerfile
ARG JUPYTERHUB_VERSION=0.9.4
FROM jupyterhub/jupyterhub:${JUPYTERHUB_VERSION}

RUN /opt/conda/bin/conda install -yq psycopg2=2.7 && \
    /opt/conda/bin/conda clean -tipsy

RUN /opt/conda/bin/pip install --no-cache \
    oauthenticator==0.8.* \
    jhub-cas-authenticator==0.3.0 \
    git+https://github.com/jupyterhub/dockerspawner.git@10d3a373370de4d1edfb6e9a092524d2ff768f31
    
COPY cull_idle_servers.py /srv/jupyterhub/cull_idle_servers.py
COPY jupyterhub_config.py /srv/jupyterhub/jupyterhub_config.py
COPY ssl /srv/jupyterhub/ssl
