---
# file: roles/jupyterhub/defaults
# type: default variables file

jh_root_dir: /srv/jupyterhub

# Version of Jupyterhub to use
JUPYTERHUB_VERSION: 0.9.4

jh_image_version: 0.9.4

jh_dockerfile_fname: Dockerfile.jupyterhub

# Name of Docker machine
DOCKER_MACHINE_NAME: jupyterhub

# Name of Docker network
DOCKER_NETWORK_NAME: jupyterhub-network

# Single-user Jupyter Notebook server container image
DOCKER_NOTEBOOK_IMAGE: jupyter/minimal-notebook:8ccdfc1da8d5

# the local image we use, after pinning jupyterhub version
LOCAL_NOTEBOOK_IMAGE: jupyterhub-user

# Notebook directory in the container.
# This will be /home/jovyan/work if the default
# This directory is stored as a docker volume for each user
DOCKER_NOTEBOOK_DIR: /home/jovyan/work

# Docker run command to use when spawning single-user containers
DOCKER_SPAWN_CMD: start-singleuser.sh

# Name of JupyterHub container data volume
DATA_VOLUME_HOST: jupyterhub-data

# Data volume container mount point
DATA_VOLUME_CONTAINER: /data

# Name of Postgres image to use
POSTGRES_DB_IMAGE: postgres:9.5-alpine

# Name of JupyterHub postgres database data volume
DB_VOLUME_HOST: jupyterhub-db-data

# Postgres volume container mount point
DB_VOLUME_CONTAINER: /var/lib/postgresql/data

# The name of the postgres database containing JupyterHub state
POSTGRES_DB: jupyterhub

# -----------------------------------------------------------------------------
# Singleuser Images
# -----------------------------------------------------------------------------

jh_singleuser_images:
  - jupyter/minimal-notebook

# ---------------------------------------------------
# JupyterHub config directories
# ---------------------------------------------------

jupyterhub_srv_dir: /srv/jupyterhub
jupyterhub_config_dir: /etc/jupyterhub
jupyterhub_log_dir: /var/log/jupyterhub

# ---------------------------------------------------
# Jupyter config directories
# ---------------------------------------------------

jupyter_config_dir: /etc/jupyter
jupyter_share_dir: /usr/local/share/jupyter
jupyter_templates_dir: "{{jupyter_config_dir}}/templates"

# ---------------------------------------------------
# IPython config directory
# ---------------------------------------------------

ipython_config_dir: /etc/ipython

# ---------------------------------------------------
# Nbgrader config directories
# ---------------------------------------------------

nbgrader_log_dir: /var/log/nbgrader
nbgrader_exchange_dir: /srv/nbgrader/exchange

# ---------------------------------------------------
# Domain / Networking / SSL
# ---------------------------------------------------

jh_port_host: 443
jh_port_container: 443
jh_public_domain: hub.example.com
jh_country_code: US
jh_csr_org_name: Example Organization
jh_csr_email: jane.doe@example.com
